spring.application.name=server
animal.name= Chien_Lion
animal.masterName=Moi
animal.race=felin
espece.nom=Chien
espece.lifespan=12
trackin=dossier_vide_rien
spring.security.user.name=admin
spring.security.user.password=secret